name: Publish
on:
  push:
    tags:
      - "*"
jobs:
  build:
    environment: npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Verify tag matches package.json version
        id: verify-tag-matches-package-version
        shell: bash
        run: |
          set -euo pipefail
          
          TAG="${GITHUB_REF_NAME}"
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG" != "$PACKAGE_VERSION" ]; then
            echo "Tag '$TAG' does not match package.json version '$PACKAGE_VERSION'"
            exit 1
          fi

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2

      - run: pnpm i --frozen-lockfile
      - run: pnpm generate-protobuf
      - run: pnpm build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
